---
abstract: 'information about all files ever released to CPAN'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-ReleaseHistory
requires:
  CPAN::DistnameInfo: '0'
  Carp: '0'
  Getopt::Long: '0'
  Moo: '0'
  MooX::Role::CachedURL: '0.06'
  autodie: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/CPAN-ReleaseHistory
  repository: https://github.com/neilbowers/CPAN-ReleaseHistory.git
version: '0.10'
